obj-$(CONFIG_KVM) += kvm/
obj-y += multiboot.o smbios.o
obj-y += pc.o pc_sysfw.o
obj-$(CONFIG_PIIX) += pc_piix.o
obj-$(CONFIG_Q35) += pc_q35.o
obj-$(CONFIG_XEN) += xen_domainbuild.o xen_machine_pv.o

obj-y += kvmvapic.o
